### ISSUE TITLE
EDITOR – widget mobile-background-image 

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#120]
- [x] pouvoir selectioner depuis le widget une image d'une gallerie (via une lightbox)
- [x] le widget renverra une url d'image redimensionné en fonction des paramètres d'initialisation du widget 
- [x] bloquer le mode de redimensionnement en **cover avec hauteur et largeur fixées**
- [x] Rajouter le fallback Microsoft
- [x] L'image de fond doit être un gif transparent par défaut
- [x] L'image ne doit pas être redimensionnée
- [x] On doit pouvoir réinitialiser l'image (bouton supprimer à côté du bouton de selection)  
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon il me faudrait un petit bout de code pour pouvoir tester un remplacement d'image.
Pourrais-tu me fournir ça dans le ticket ?

là actuellement je teste avec ceci : 

```html
<dd style="height: 100px; background: no-repeat center center; background-image: url('http://dummyimage.com/200x100/666666/fff'); -ko-background-image: url(@[firstBgimage]);" ></dd>


<dd style="height: 100px; text-align: center">
  <table width="200">
    <tr>
      <td background="http://dummyimage.com/200x100/666666/fff" style="height:100px; -ko-attr-background: @secondBgimage;"></td>
    </tr>
  </table>
</dd>
```

**Comment by Hiswe** [comment]
@Frolipon C'est en place 

le premier bloc est composé de deux background-images :

https://badsender-test.herokuapp.com/editor/5948ea60c90b45000c8e866b

Dis moi si l'interface te conviens.

Pour ce qui est du markup, tu peux regarder le code source du template :

- [le code du blockdef](https://github.com/goodenough/mosaico/blob/widget-bgimage/templates/sub-themes/template-sub-themes.html#L65-L69)
- [le code html](https://github.com/goodenough/mosaico/blob/widget-bgimage/templates/sub-themes/template-sub-themes.html#L318-L356)

Il faudra donc bien spécifier la taille voulue :

```sass
bgimage {
  label: Background Image;
  widget: bgimage;
  // taille voulue du background au format [width]x[height]
  size: 200x100;
}
```

**Comment by Frolipon** [comment]
L'interface me convient!

Pour ce qui est du style, ce n'est pas indispensable mais si c'est possible, ce serait le premier pas vers de l'affichage mobile (les remplacements d'images en rendu mobile se font via la balise style et des images de background)

Pour ce qui est de la taille, est-ce que les paramètres sont passés dans le template ou bien ils sont passés à une méthode quelque part qui fait un resize?

**Comment by Hiswe** [comment]
### todo

1. à rajouter au template, en étant l'enfant direct du tag qui porte le background :

```html
<!--[if gte mso 9]>
  <v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
    <v:fill type="tile" src="images/texture.jpg" color="#1b1c1c"/>
  </v:background>
<![endif]-->
```
2. L'image de fond doit être un gif transparent par défaut
3. L'image ne doit pas être redimensionnée
4. On doit pouvoir réinitialiser l'image (bouton supprimer à côté du bouton de selection)

**Comment by Hiswe** [comment]
@Frolipon les améliorations ont été poussées sur le dev

https://badsender-test.herokuapp.com/editor/59507fbab93667000cf1629c

**Comment by Hiswe** [comment]
@Frolipon passé en stage. J'ai besoin du dev pour le #113

**Comment by Frolipon** [comment]
Good pour moi, sous réserve du ticket https://github.com/goodenough/mosaico/issues/100
