### ISSUE TITLE
COMPANY – migration

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#45]
Pour résoudre les tickets #18 et #20 
- [x] Étapes de dev :
  - [x] Interface de création des sociétés
  - [x] Interface de migration d'un utilisateur
  - [x] Modification _home utilisateur_ : un utilisateur voit tout les templates et les créations de sa société (lié à #19)
  - [x] Script de copie DB prod -> DB dev
  - [x] Script de copies DB stage -> DB prod (#44) 
  - [x] Script de backup de DB prod
  - [x] Création des pages de maintenance/erreur (#26)
  - [x] Corrections retours Grégory
- [x] déploiement dev :
  - [x] Test avec Badsender d'une migration à partir de la DB de dev
- [x] déploiement stage :
  - [x] Test avec Badsender d'une migration à partir d'un copie DB de la prod
  - [x] Mode maintenance de l'application prod (lié à #26)
  - [x] Modification depuis le stage d'une copie de la DB prod
  - [x] Déploiement de la DB modifiée sur la prod
  - [x] Déploiement code en production 
  - [x] Enlever le mode maintenance

**Comment by Hiswe** [comment]
@Frolipon Si tu veux tu peux faire un test de migration sur le dev.

J'ai corrigé les différents points que tu avais relevé. 
Dis moi si ça te va

**Comment by Frolipon** [comment]
Ça me semble tout bon. Reste juste à se coordonner pour monter ça en stage/prod.

J'attends un retour client sur leurs horaires pour éviter de leurs faire des sueurs froides avec la page de maintenance ;-)
Je te tiens au courant dès que j'en sais plus afin qu'on puisse finaliser ça!

**Comment by Frolipon** [comment]
Migration en prod effectuée avec succès! 👍 

Thanks
